name: Detect-Secrets Scan for Current Repository

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  detect-secrets-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Current Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure full history for accurate scanning

    - name: Install detect-secrets
      run: |
        python3 -m pip install detect-secrets

    - name: Run Detect-Secrets Scan
      run: |
        detect-secrets scan > detect_secrets_baseline.json
        echo "Detect-Secrets scan completed. Results saved to detect_secrets_baseline.json."

    - name: Audit and Format Results
      run: |
        yes s | detect-secrets audit detect_secrets_baseline.json | tee detect_secrets_audit_results.txt
        echo "Detect-Secrets audit completed. Results saved to detect_secrets_audit_results.txt."

    - name: Display Results in Logs
      run: |
        cat detect_secrets_audit_results.txt

    - name: Upload Results as Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: detect-secrets-results
        path: |
          detect_secrets_baseline.json
          detect_secrets_audit_results.txt
