name: Detect-Secrets Scan

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  detect-secrets-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install detect-secrets
      run: |
        python3 -m pip install detect-secrets

    - name: Run Detect-Secrets Scan
      run: |
        detect-secrets scan > detect_secrets_report.json

    - name: Upload Detect-Secrets report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: detect-secrets-scan-results
        path: detect_secrets_report.json
