name: Security Scans (Trivy, Detect-Secrets, Semgrep, and PDF Report)

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current repository
    - name: Checkout Current Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Step 2: Run Trivy Repo Scan
    - name: Run Trivy Repo Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        format: 'json'
        output: 'trivy_scan_results.json'

    # Step 3: Install Dependencies for Detect-Secrets and Semgrep
    - name: Install Dependencies
      run: |
        python3 -m pip install detect-secrets semgrep fpdf

    # Step 4: Run Detect-Secrets Scan
    - name: Run Detect-Secrets Scan
      run: |
        detect-secrets scan > detect_secrets_baseline.json
        yes s | detect-secrets audit detect_secrets_baseline.json | tee detect_secrets_audit_results.txt

    # Step 5: Run Semgrep Scan with OWASP Top 10 Ruleset
    - name: Run Semgrep Scan
      run: |
        semgrep --config "p/owasp-top-ten" --output semgrep_results.json --json
      env:
        SEMGREP_ALLOW_FETCH: 1

    # Step 6: Fetch and Run the Python Script to Generate PDF
    - name: Generate PDF Report
      run: |
        python3 generate_pdf.py

    # Step 7: Upload PDF Report as Artifact
    - name: Upload PDF Report
      uses: actions/upload-artifact@v4
      with:
        name: security-scan-report
        path: security_scan_report.pdf
