name: Security Scans (Trivy and Detect-Secrets)

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  security-scans:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the current repository
    - name: Checkout Current Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Step 2: Run Trivy Repo Scan
    - name: Run Trivy Repo Scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs' # File system scan
        format: 'json'
        output: 'trivy_scan_results.json'
      continue-on-error: true
      # This ensures the workflow doesn't fail even if vulnerabilities are found

    # Step 3: Install Detect-Secrets
    - name: Install Detect-Secrets
      run: |
        python3 -m pip install detect-secrets

    # Step 4: Run Detect-Secrets Scan
    - name: Run Detect-Secrets Scan
      run: |
        detect-secrets scan > detect_secrets_baseline.json
        yes s | detect-secrets audit detect_secrets_baseline.json | tee detect_secrets_audit_results.txt
        echo "Detect-Secrets scan completed. Results saved to detect_secrets_audit_results.txt."

    # Step 5: Display results in logs
    - name: Display Trivy Results
      run: |
        echo "=== Trivy Results ==="
        cat trivy_scan_results.json

    - name: Display Detect-Secrets Results
      run: |
        echo "=== Detect-Secrets Results ==="
        cat detect_secrets_audit_results.txt

    # Step 6: Upload results as artifacts
    - name: Upload Trivy Results
      uses: actions/upload-artifact@v4
      with:
        name: trivy-scan-results
        path: trivy_scan_results.json

    - name: Upload Detect-Secrets Results
      uses: actions/upload-artifact@v4
      with:
        name: detect-secrets-scan-results
        path: |
          detect_secrets_baseline.json
          detect_secrets_audit_results.txt
